refactor: use overlapping grid elements to grow/shrink textarea's height
vaadin/vaadin-text-field pull request #578
Opened 2021-06-23 14:56 UTC by fhdhsni

shady css compiles:

`foo ::slotted(bar)`

to:

`foo > bar`

which results in breaking some of the styles with the addition of
`.textarea-wrapper`. To prevent that I had to copy and paste some of the
styles from vaadin-text-field-mixin.html to vaadin-text-area.html and
change the selector from `[part="input-field"] ::slotted(textarea)` to
`.textarea-wrapper ::slotted(textarea)`

2021-06-23 14:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-text-field?pullRequest=578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-text-field?pullRequest=578) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-text-field?pullRequest=578) it.</sub>

2021-06-28 12:55 UTC, yuriy-fix reviewed
There is minor visual regression on IE11 (text-color, size). 
Comparing `2.8` and `refactor/text-area-auto-height` branches:

![Capture-2](https://user-images.githubusercontent.com/29372419/123639794-3470d280-d829-11eb-9cac-a12ffd1504df.PNG)
![Capture](https://user-images.githubusercontent.com/29372419/123639798-35a1ff80-d829-11eb-8314-db6f58ed59ab.PNG)

2021-07-29 06:45 UTC, alvarezguille requested changes
Added some initial contents, I'll continue testing locally

2021-07-29 06:45 UTC, alvarezguille commented on src/vaadin-text-area.html
> +            // input.style.padding = '0';
Please remove commented code

2021-07-29 06:45 UTC, alvarezguille commented on src/vaadin-text-area.html
> +          // input.style.removeProperty('padding');
Please remove commented code

2021-07-29 06:45 UTC, alvarezguille commented on src/vaadin-text-area.html
> +          /* padding: 0 0.25em; */
Please remove commented code

2021-07-29 06:45 UTC, alvarezguille commented on src/vaadin-text-area.html
> +        /* color: var(--lumo-body-text-color); */
Please remove commented code

2021-07-29 06:45 UTC, alvarezguille commented on src/vaadin-text-area.html
> +        /* reset ua stylesheet */
what's `ua` in this comment?

2021-07-29 08:56 UTC, alvarezguille requested changes
I'm getting this behavior on initial load of the demos in ios safari 13.1, it happens only on the initial load, and get's fixed after interacting
![image](https://user-images.githubusercontent.com/9820084/127462700-adbbcae0-d775-493e-9e9f-fd52287c4703.png)
@fhdhsni @hdamr could you check if the issue is related to the change?

2021-09-13 06:36 UTC, sissbruecker commented
Obsolete due to #581

2021-09-13 06:36 UTC, closed without merging